In [1]:
# MLP with automatic validation set
from keras.models import Sequential
from keras.layers import Dense
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn import metrics

Using TensorFlow backend.


In [26]:
def purity_score(y_true, y_pred):
    # compute contingency matrix (also called confusion matrix)
    contingency_matrix = metrics.cluster.contingency_matrix(y_true, y_pred)
    # return purity
    return np.sum(np.amax(contingency_matrix, axis=0)) / np.sum(contingency_matrix) 

In [49]:
def purity_score_per_cluster(data, N):
    return (data['y'].value_counts().max() / N)

In [27]:
# fix random seed for reproducibility
# seed = 6
# np.random.seed(seed)

In [28]:
# load pima indians dataset
#dataset = numpy.loadtxt("D:/Neural_nets_course_Dataset/pima_indians_diabetes_data.csv", delimiter=",")
dataset = pd.read_csv('E:/Academic/Neural Networks/Assignment_2/iris.txt', delimiter=',', names = ['a','b','c','d','y'])

In [29]:
dataset.head()

a    b    c    d  y
0  5.1  3.5  1.4  0.2  1
1  4.9  3.0  1.4  0.2  1
2  4.6  3.1  1.5  0.2  1
3  5.0  3.6  1.4  0.2  1
4  4.6  3.4  1.4  0.3  1

In [30]:
len(dataset)

150

In [31]:
X = dataset.iloc[:,0:4].values
Y = dataset.iloc[:,4].values

In [32]:
# initilaize to very small random values
weight_matrix = np.random.rand(3, 4)
weight_matrix = preprocessing.normalize(weight_matrix, norm='l2')

In [33]:
weight_matrix

array([[0.57747178, 0.47902018, 0.48758658, 0.44645866],
       [0.76267533, 0.11942354, 0.48981408, 0.40515   ],
       [0.62375013, 0.34441463, 0.17431373, 0.67965364]])

In [34]:
# l2-normalize the samples (rows).
X_normalized = preprocessing.normalize(X, norm='l2')
X_normalized = np.array(X_normalized)

In [35]:
cluster_indexes = []
alpha = 0.3

for i in range(500):
    cluster_indexes = []
    for index,iterator in enumerate(X_normalized):
        out_neuron_vector = np.dot(weight_matrix, X_normalized[index])
        max_index = np.argmax(out_neuron_vector)
        # add cluster value for each tuple
        cluster_indexes.append(max_index + 1)
        # retrieve Wk vector
        Wk = weight_matrix[max_index,:]
        # update the Wk vector
        pwx = alpha * np.subtract(X_normalized[index], Wk)
        Wk = np.add(Wk, pwx)
        # normalize Wk
        euclidean_norm = np.sqrt(sum(Wk**2))
        Wk = Wk / euclidean_norm
        # add Wk to original weight matrix location
        weight_matrix[max_index,:] = Wk

In [36]:
np.unique(cluster_indexes)

array([1, 2], dtype=int64)

In [37]:
len(cluster_indexes)

150

In [56]:
temp_dataset = dataset
temp_dataset['cluster'] = cluster_indexes

purity_score_cluster1 = 0.0
purity_score_cluster2 = 0.0
purity_score_cluster3 = 0.0

#purity score for cluster 1
cluster1_dataset = temp_dataset[temp_dataset['cluster'] == 1]
if len(cluster1_dataset) != 0:
    purity_score_cluster1 = purity_score_per_cluster(cluster1_dataset, len(dataset))

#purity score for cluster 2
cluster2_dataset = temp_dataset[temp_dataset['cluster'] == 2]
if len(cluster2_dataset) != 0:
    purity_score_cluster2 = purity_score_per_cluster(cluster2_dataset, len(dataset))

#purity score for cluster 3
cluster3_dataset = temp_dataset[temp_dataset['cluster'] == 3]
if len(cluster3_dataset) != 0:
    purity_score_cluster3 = purity_score_per_cluster(cluster3_dataset, len(dataset))

print('Purity score for cluster 1: ', purity_score_cluster1)
print('Purity score for cluster 2: ', purity_score_cluster2)
print('Purity score for cluster 3: ', purity_score_cluster3)
print('Total purity score: ', purity_score(Y, cluster_indexes))

Purity score for cluster 1:  0.3333333333333333
Purity score for cluster 2:  0.3333333333333333
Purity score for cluster 3:  0.0
Total purity score:  0.6666666666666666


In [55]:
purity_score(Y, cluster_indexes)

0.6666666666666666

In [4]:
a=np.array([1,2,3,4])
b=np.argmax(a)
print(a[b])

3


In [52]:
weight_mat = np.random.randn(3, 4)
a = [[1,2,3,4], [3, 5, 6, 8]]
#out_vector = np.dot(weight_mat, a)
    

In [64]:
weight_mat

array([[-0.34329247,  0.7205635 , -0.02352852,  0.60198416],
       [-0.19645069,  0.0851739 ,  0.94029928,  0.26455584],
       [-0.2471944 ,  0.8458623 , -0.01673924, -0.47236819]])

In [54]:
a

[[1, 2, 3, 4], [3, 5, 6, 8]]

In [55]:
a = np.array(a)

In [69]:
for index, x in enumerate(a):
    print(np.subtract(weight_mat[0], a[index]))

[-1.34329247 -1.2794365  -3.02352852 -3.39801584]
[-3.34329247 -4.2794365  -6.02352852 -7.39801584]


In [68]:
for index, x in enumerate(a):
    print(np.dot(weight_mat, np.array(a[index])))

[ 3.43518562  3.85301831 -0.49516027]
[ 7.24764227  7.59475983 -0.39165264]


In [57]:
weight_mat

array([[-0.56079862,  1.17710424, -0.03843592,  0.98339438],
       [-0.30294356,  0.11643074,  1.40203911,  0.37755632],
       [-0.12474052,  0.42684341, -0.00844704, -0.23836888]])

In [58]:
weight_mat = preprocessing.normalize(weight_mat, norm='l2')

In [59]:
weight_mat

array([[-0.34329247,  0.7205635 , -0.02352852,  0.60198416],
       [-0.20361642,  0.0782562 ,  0.94234777,  0.25376564],
       [-0.2471944 ,  0.8458623 , -0.01673924, -0.47236819]])

In [60]:
a_normalized = preprocessing.normalize(a, norm='l2')

In [66]:
a_normalized

array([[0.18257419, 0.36514837, 0.54772256, 0.73029674],
       [0.25916053, 0.43193421, 0.51832106, 0.69109474]])

In [67]:
a_normalized * 2

array([[0.36514837, 0.73029674, 1.09544512, 1.46059349],
       [0.51832106, 0.86386843, 1.03664211, 1.38218948]])

In [62]:
for index,iterator in enumerate(a_normalized):
    print(a_normalized[index])
    out_neuron_vector = np.dot(weight_mat, a_normalized[index])
    print('out_neuron_vector:')
    print(out_neuron_vector)
    b = np.argmax(out_neuron_vector)
    print('index:', b + 1)
    print('extracted mat loc:', weight_mat[b,:])
    pxw = np.subtract(a_normalized[index], weight_mat[b,:])
    Wk = np.add(weight_mat[b,:], (0.01 * pxw))
    
    euclidean_norm = np.sqrt(sum(Wk**2))
    Wk = Wk / euclidean_norm
    print('Wk:')
    print(Wk)
    weight_mat[b,:] = Wk
    print('updated weight matrix:')
    print(weight_mat)
    

[0.18257419 0.36514837 0.54772256 0.73029674]
out_neuron_vector:
[ 0.62717622  0.69286937 -0.09040348]
index: 2
extracted mat loc: [-0.20361642  0.0782562   0.94234777  0.25376564]
Wk:
[-0.20036467  0.08137292  0.94126789  0.25932065]
updated weight matrix:
[[-0.34329247  0.7205635  -0.02352852  0.60198416]
 [-0.20036467  0.08137292  0.94126789  0.25932065]
 [-0.2471944   0.8458623  -0.01673924 -0.47236819]]
[0.25916053 0.43193421 0.51832106 0.69109474]
out_neuron_vector:
[ 0.62610093  0.65031523 -0.03383363]
index: 2
extracted mat loc: [-0.20036467  0.08137292  0.94126789  0.25932065]
Wk:
[-0.19645069  0.0851739   0.94029928  0.26455584]
updated weight matrix:
[[-0.34329247  0.7205635  -0.02352852  0.60198416]
 [-0.19645069  0.0851739   0.94029928  0.26455584]
 [-0.2471944   0.8458623  -0.01673924 -0.47236819]]


In [39]:
preprocessing.normalize([1, 2, 3], norm='l2')

ValueError: Expected 2D array, got 1D array instead:
array=[1. 2. 3.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [57]:
import math
# Example points in 3-dimensional space...
x = (5, 6, 7)
y = (8, 9, 9)
distance = math.sqrt(sum([(a - b) ** 2 for a, b in zip(x, y)]))
print("Euclidean distance from x to y: ",distance)

Euclidean distance from x to y:  4.69041575982343


In [71]:
from sklearn.metrics.pairwise import euclidean_distances

x = [[5, 6, 7], [1, 1, 1], [2, 2, 2]]
y = [8, 9, 9]
#np.sqrt(np.sum(np.square(np.array(x)-np.array(y).reshape(1,3)),axis=0))
np.linalg.norm(np.array(x)-np.array(y), axis=1, ord=2)

array([ 4.69041576, 13.3041347 , 11.5758369 ])