In [1]:
import os
import numpy as np
import shutil

In [9]:
train_dir = "C:/Users/hp/Desktop/SL_DR_Dataset/Disease_Grading/Original_Images/classified_train/"

# Create folders for  training data and validation randomly splitted
new_train = os.mkdir("C:/Users/hp/Desktop/SL_DR_Dataset/Disease_Grading/Original_Images/train_test_splitter/train")
new_valid = os.mkdir("C:/Users/hp/Desktop/SL_DR_Dataset/Disease_Grading/Original_Images/train_test_splitter/validation")

new_train_dir  = "C:/Users/hp/Desktop/SL_DR_Dataset/Disease_Grading/Original_Images/train_test_splitter/train/"
new_valid_dir = "C:/Users/hp/Desktop/SL_DR_Dataset/Disease_Grading/Original_Images/train_test_splitter/validation/"

In [10]:
# Get all the classes from the original train directory
classes = os.listdir(train_dir)

# Create target folders in the new train data directory
for c in classes:
    os.mkdir(new_train_dir + c)

# Create validation folders in the new validation data directory
for c in classes:
    os.mkdir(new_valid_dir + c)

In [11]:
for level in classes:
    retina_root = train_dir + level + '/'
    retina_new_train = new_train_dir + level + '/'
    retina_new_valid = new_valid_dir + level + '/'
    retina_root_list = os.listdir(retina_root)
    test_size = 0.7
    split_index = int(0.7*len(retina_root_list))
    np.random.shuffle(retina_root_list)
    train_list = retina_root_list[:split_index]
    valid_list = retina_root_list[split_index:]
    print("train_list count:" + str(len(train_list)))
    print("valid_list count:" + str(len(valid_list)))
    for image in train_list :
        source = retina_root + image
        target = retina_new_train + image
        shutil.copy(source,target)
    for image in valid_list:
        source = retina_root + image
        target = retina_new_valid + image
        shutil.copy(source,target)

train_list count:93
valid_list count:41
train_list count:14
valid_list count:6
train_list count:95
valid_list count:41
train_list count:51
valid_list count:23
train_list count:34
valid_list count:15


In [8]:
import numpy as np
LA = np.linalg

a = np.array([[1, 3, 4], [5, 6, 9], [1, 2, 3], [7, 6, 8]])
print(a)
# [[1 3 4]
#  [5 6 9]
#  [1 2 3]
#  [7 6 8]]
U, s, Vh = LA.svd(a, full_matrices=False)
assert np.allclose(a, np.dot(U, np.dot(np.diag(s), Vh)))

s[2:] = 0
new_a = np.dot(U, np.dot(np.diag(s), Vh))
print(new_a)

[[1 3 4]
 [5 6 9]
 [1 2 3]
 [7 6 8]]
[[1.02206755 2.77276308 4.14651336]
 [4.9803474  6.20236935 8.86952026]
 [0.99786077 2.02202837 2.98579698]
 [7.01104783 5.88623677 8.07335002]]


In [10]:
# Singular-value decomposition
U,s,VT = np.linalg.svd(a)
# create m x n Sigma matrix
Sigma = np.zeros((a.shape[0], a.shape[1]))
# populate Sigma with n x n diagonal matrix
Sigma[:a.shape[1], :a.shape[1]] = np.diag(s)

Sigma = Sigma[:, :2]
VT = VT[:2, :]
B = U.dot(Sigma.dot(VT))
print(B)

[[1.02206755 2.77276308 4.14651336]
 [4.9803474  6.20236935 8.86952026]
 [0.99786077 2.02202837 2.98579698]
 [7.01104783 5.88623677 8.07335002]]
